
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 22;
  public static final int STRING_LITERAL = 33;
  public static final int MULT = 9;
  public static final int LTEQ = 21;
  public static final int FEATURE = 4;
  public static final int INTEGER = 12;
  public static final int LPAREN = 10;
  public static final int MINUS = 7;
  public static final int RPAREN = 11;
  public static final int REAL_LITERAL = 35;
  public static final int SEMICOLON = 17;
  public static final int LT = 19;
  public static final int COMMA = 18;
  public static final int CLASS = 2;
  public static final int DIV = 8;
  public static final int UNTIL = 29;
  public static final int LOOP = 30;
  public static final int PLUS = 6;
  public static final int IF = 23;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FROM = 28;
  public static final int REAL = 13;
  public static final int COLON = 15;
  public static final int ELSE = 25;
  public static final int CREATE = 3;
  public static final int THEN = 24;
  public static final int END = 27;
  public static final int STRING = 14;
  public static final int LOCAL = 5;
  public static final int COLEQ = 16;
  public static final int GT = 20;
  public static final int PRINT = 31;
  public static final int DO = 26;
  public static final int INTEGER_LITERAL = 34;
  public static final int IDENTIFIER = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "CREATE",
  "FEATURE",
  "LOCAL",
  "PLUS",
  "MINUS",
  "DIV",
  "MULT",
  "LPAREN",
  "RPAREN",
  "INTEGER",
  "REAL",
  "STRING",
  "COLON",
  "COLEQ",
  "SEMICOLON",
  "COMMA",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "IF",
  "THEN",
  "ELSE",
  "DO",
  "END",
  "FROM",
  "UNTIL",
  "LOOP",
  "PRINT",
  "IDENTIFIER",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "REAL_LITERAL"
  };
}

